def menu():
   print("Selamat datang di BNMO!")
   print("================ MAIN MENU ===============")
   print("-> register")
   print("-> login")
   print("-> tambah_game")
   print("-> ubah_game")
   print("-> ubah_stok")
   print("-> list_game_toko")
   print("-> buy_game")
   print("-> list_game")
   print("-> search_my_game")
   print("-> search_game_at_store")
   print("-> topup")
   print("-> riwayat")
   print("-> help")
   print("-> save")
   print("-> exit")