def menu():
   print("\nSelamat datang di BNMO!\n")
   print("================ MAIN MENU ===============")
   print("-> 1. register")
   print("-> 2. login")
   print("-> 3. tambah_game")
   print("-> 4. ubah_game")
   print("-> 5. ubah_stok")
   print("-> 6. list_game_toko")
   print("-> 7. buy_game")
   print("-> 8. list_game")
   print("-> 9. search_my_game")
   print("-> 10. search_game_at_store")
   print("-> 11. topup")
   print("-> 12. riwayat")
   print("-> 13. help")
   print("-> 14. save")
   print("-> 15. exit")
   print("=========================================")